### ISSUE TITLE
please convert this command

### ISSUE THREAD

**Issue by yashmoyal** [mspnp/azure-databricks-streaming-analytics#20]
"docker run -v `pwd`/DataFile:/DataFile --env-file=onprem/main.env dataloader:latest"

can anyone please convert this command into windows command as I am not able to run it

my directory hierarchy is D:\azure-databricks-streaming-analytics\DataFile

please help me!!

**Comment by skabou** [comment]
I know this was posted some time ago, but this may work for you:

`docker run -v D:\azure-databricks-streaming-analytics\DataFile:/DataFile --env-file=onprem\main.env dataloader:latest`
