### ISSUE TITLE
java.lang.NullPointerException in GeoFinder.getNeighborhood()

### ISSUE THREAD

**Issue by lucian-d** [mspnp/azure-databricks-streaming-analytics#3]
Hi there,

I've managed to set the project up, Azure Databricks job is running but failing due to an exception when mapping coordinates into neighborhood name.  

I've attached the log. Can you check it please?

Please note that ZillowNeighborhoods-NY.zip was no available at the original posted URL, so I got it from the link below instead. 

https://github.com/Azure/LearnAnalytics-AnalyzingBigDataWithMRS/tree/master/ZillowNeighborhoods-NY

Thanks and regards,
Lucian

[GeoFinder_getNeighborhood_error_log.txt](https://github.com/mspnp/azure-databricks-streaming-analytics/files/4361198/GeoFinder_getNeighborhood_error_log.txt)

**Comment by jocontr** [comment]
Thank you for bringing up this issue. It is currently being investigated.
