### ISSUE TITLE
Method in the jar doesn't match

### ISSUE THREAD

**Issue by robinsonmhj** [mspnp/azure-databricks-streaming-analytics#4]
Hi there,

It seems that the gt-shapefile.jar doesn't exist anymore in https://repo.boundlessgeo.com/, I tried several different repo, it is not there anymore. So I download it from https://sourceforge.net/projects/geotools/. But the package directory is total different, the code cannot compile, see the error below. Can you please point me the right URL to the above jar

![image](https://user-images.githubusercontent.com/7291531/79500324-425a7f00-7ffa-11ea-874f-e1b0062f5b8e.png)

**Comment by kirpasingh** [comment]
https://github.com/mspnp/azure-databricks-streaming-analytics/pull/5 ensures no build errors are encountered.
